# Generated by Django 5.2.17 on 2026-08-27 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-start_date', '-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_ride_da_af5673_idx',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='expected_arrival_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='expected_return_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_date',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['start_date', 'status'], name='rides_ride_start_d_59a757_idx'),
        ),
    ]
