# Generated by Django 5.2.17 on 2026-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
