# Generated by Django 5.2.17 on 2026-08-27 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits, optional leading +).', regex='^\\+?[0-9]{10,15}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive riders cannot log in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
